### PR TITLE
storage: add a DiskMap and DiskMapIterator interface

### PR DESCRIPTION
**Pull request by asubiotto**
Left a bunch of TODOs for unresolved questions. I'll also add an interface to batch writes but wanted to see what you thought of the basics.

---
This change is [Reviewable](https://reviewable.io/reviews/arjunravinarayan/cockroach/10)

### CODE REVIEW

**Comment by rjnn** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/storage/engine/disk_map.go, line 17 at r1](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Km2h32QcrIVwlX62mve:-Km2h32QcrIVwlX62mvf:b-9m4xmm) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/e0cd2d773bb12569eeef24c4032bef1613ee72c3/pkg/storage/engine/disk_map.go#L17)):*
> ```Go
> // Author: Alfonso Subiotto Marqués (alfonso@cockroachlabs.com)
> 
> // TODO(asubiotto): Not sure what package this should be in.
> ```

`distsqlrun`

---

*[pkg/storage/engine/disk_map.go, line 48 at r1](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Km2i-OZkLUxjNhOk5jW:-Km2i-OZkLUxjNhOk5jX:b-eapy1n) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/e0cd2d773bb12569eeef24c4032bef1613ee72c3/pkg/storage/engine/disk_map.go#L48)):*
> ```Go
> 
> // DiskMap is an on-disk map. Keys are iterated over in sorted order.
> type DiskMap interface {
> ```

`SortedMapOnDisk` might be a better name. Gets across that it's a map that also has a sort defined on it. This is an elegant splitting of the interface to separate the KV from the Iterator, I like it.

---

*[pkg/storage/engine/disk_map.go, line 56 at r1](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Km2kao-OVtW97KsNFvo:-Km2kao-OVtW97KsNFvp:b-kbql0f) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/e0cd2d773bb12569eeef24c4032bef1613ee72c3/pkg/storage/engine/disk_map.go#L56)):*
> ```Go
> }
> 
> type RocksDBMap struct {
> ```

`SortedMapWithRocksDB`?

---

*[pkg/storage/engine/disk_map.go, line 57 at r1](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Km2kRlolyM8G3pHFW-B:-Km2kRlolyM8G3pHFW-C:b-esf9vk) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/e0cd2d773bb12569eeef24c4032bef1613ee72c3/pkg/storage/engine/disk_map.go#L57)):*
> ```Go
> 
> type RocksDBMap struct {
> 	store *RocksDB
> ```

Put a TODO in here saying that eventually this struct will also have an in-memory map and some memory accounting stuff as well.

---

*[pkg/storage/engine/disk_map.go, line 68 at r1](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Km2l_z8P9XIdzgCzrFn:-Km2koGmEGi5kueBY3rP:b3o402t) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/e0cd2d773bb12569eeef24c4032bef1613ee72c3/pkg/storage/engine/disk_map.go#L68)):*
> ```Go
> var _ DiskMapIterator = RocksDBMapIterator{}
> 
> const rocksDBMapPath = "rocksdb_temp"
> ```

So this is basically going down a wrong path. Each Map won't have its own backing RocksDB instance. There will be a single RocksDB instance per node. Instead, the construct  will be passed a reference to a RocksDB instance, and it will be allocated a unique key-prefix, which it will have to prefix to each key on read/write. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10)*

**Comment by asubiotto** [comment]
Review status: 0 of 2 files reviewed at latest revision, 5 unresolved discussions.

---

*[pkg/sql/distsqlrun/disk_map.go, line 17 at r1](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Km2h32QcrIVwlX62mve:-Km7TIvq7ntIs9c6EXmx:b-896fix) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/e0cd2d773bb12569eeef24c4032bef1613ee72c3/pkg/sql/distsqlrun/disk_map.go#L17)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

`distsqlrun`
</blockquote></details>

Done.

---

*[pkg/storage/engine/disk_map.go, line 48 at r1](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Km2i-OZkLUxjNhOk5jW:-Km5xNsllNwORCs4PS3o:b-rrb9j6) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/e0cd2d773bb12569eeef24c4032bef1613ee72c3/pkg/storage/engine/disk_map.go#L48)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

`SortedMapOnDisk` might be a better name. Gets across that it's a map that also has a sort defined on it. This is an elegant splitting of the interface to separate the KV from the Iterator, I like it.
</blockquote></details>

Maybe `SortedDiskMap`?

---

*[pkg/storage/engine/disk_map.go, line 56 at r1](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Km2kao-OVtW97KsNFvo:-Km6AlxzNb99VP4DyL4G:bng0m15) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/e0cd2d773bb12569eeef24c4032bef1613ee72c3/pkg/storage/engine/disk_map.go#L56)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

`SortedMapWithRocksDB`?
</blockquote></details>

I don't like that name. I think RocksDB in the name already conveys that keys are sorted. Maybe `SortedRocksDBMap`? I don't feel strongly about this though so let me know your preference.

---

*[pkg/storage/engine/disk_map.go, line 57 at r1](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Km2kRlolyM8G3pHFW-B:-Km5xcvOkZYpFPzKnfXO:b-vg5h02) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/e0cd2d773bb12569eeef24c4032bef1613ee72c3/pkg/storage/engine/disk_map.go#L57)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

Put a TODO in here saying that eventually this struct will also have an in-memory map and some memory accounting stuff as well.
</blockquote></details>

I think that the in-memory map should be at a higher level (although I agree that memory/disk usage accounting will happen here). This is what I'm thinking for how this will be implemented in the sorter (first pass implementation):

- Sorter uses a normal `RowContainer` that eventually returns a `memory budget exceeded` error.
- Sorter constructs a `RowContainer` that is backed by disk (let's call it `DiskRowContainer` for the purposes of this explanation) from this normal `RowContainer`. The sorter will pass this `DiskRowContainer` its processor ID (unique across the cluster I assume?) to use as a key prefix as well as a reference to the DistSQL RocksDB instance. This constructor will also have an option to keep track or not of duplicates (I haven't thought much about this but will flesh it out in code ASAP)
- The `DiskRowContainer` flushes out the current in-memory rows and buffers writes to the underlying `DiskMap`
- If the `DiskMap` hits a memory limit, it will bubble up an error.
- The Sorter requests the rows and they are read up from the `DiskMap` through the `DiskRowContainer`.

Keeping the memory map at the `DiskRowContainer` will avoid the complexity of having to keep a map in DiskMap and maintaining the invariant that we iterate over all the keys stored in the DiskMap in sorted order.

I'm guessing similar designs (probably with a more complex intermediary for other processors like the HashJoiner) but I have to think about it more. The thing is that `DiskRowContainer` is pretty simple for the `Sorter` but other intermediaries will need probably need some more specific logic (e.g. appending to values)

---

*[pkg/storage/engine/disk_map.go, line 68 at r1](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Km2l_z8P9XIdzgCzrFn:-Km5yCiPU3LvAGLErz14:b-5apayl) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/e0cd2d773bb12569eeef24c4032bef1613ee72c3/pkg/storage/engine/disk_map.go#L68)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

So this is basically going down a wrong path. Each Map won't have its own backing RocksDB instance. There will be a single RocksDB instance per node. Instead, the construct  will be passed a reference to a RocksDB instance, and it will be allocated a unique key-prefix, which it will have to prefix to each key on read/write. 
</blockquote></details>

Changed. I assume we will pass in the processor ID as a key prefix?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10)*

**Comment by rjnn** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/distsqlrun/disk_map.go, line 48 at r1](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Km2i-OZkLUxjNhOk5jW:-KmCG3qKGZor3E2-dANH:bb74ce2) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/e0cd2d773bb12569eeef24c4032bef1613ee72c3/pkg/sql/distsqlrun/disk_map.go#L48)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe `SortedDiskMap`?
</blockquote></details>

Sure

---

*[pkg/sql/distsqlrun/disk_map.go, line 56 at r1](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Km2kao-OVtW97KsNFvo:-KmCG4aM348CbJgYrXNa:b-ia1bnc) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/e0cd2d773bb12569eeef24c4032bef1613ee72c3/pkg/sql/distsqlrun/disk_map.go#L56)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I don't like that name. I think RocksDB in the name already conveys that keys are sorted. Maybe `SortedRocksDBMap`? I don't feel strongly about this though so let me know your preference.
</blockquote></details>

OK. You're right. RocksDB does imply sorting.

---

*[pkg/sql/distsqlrun/disk_map.go, line 57 at r1](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Km2kRlolyM8G3pHFW-B:-KmCG9ab-b7SFmpCpFkL:bdxnslx) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/e0cd2d773bb12569eeef24c4032bef1613ee72c3/pkg/sql/distsqlrun/disk_map.go#L57)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think that the in-memory map should be at a higher level (although I agree that memory/disk usage accounting will happen here). This is what I'm thinking for how this will be implemented in the sorter (first pass implementation):

- Sorter uses a normal `RowContainer` that eventually returns a `memory budget exceeded` error.
- Sorter constructs a `RowContainer` that is backed by disk (let's call it `DiskRowContainer` for the purposes of this explanation) from this normal `RowContainer`. The sorter will pass this `DiskRowContainer` its processor ID (unique across the cluster I assume?) to use as a key prefix as well as a reference to the DistSQL RocksDB instance. This constructor will also have an option to keep track or not of duplicates (I haven't thought much about this but will flesh it out in code ASAP)
- The `DiskRowContainer` flushes out the current in-memory rows and buffers writes to the underlying `DiskMap`
- If the `DiskMap` hits a memory limit, it will bubble up an error.
- The Sorter requests the rows and they are read up from the `DiskMap` through the `DiskRowContainer`.

Keeping the memory map at the `DiskRowContainer` will avoid the complexity of having to keep a map in DiskMap and maintaining the invariant that we iterate over all the keys stored in the DiskMap in sorted order.

I'm guessing similar designs (probably with a more complex intermediary for other processors like the HashJoiner) but I have to think about it more. The thing is that `DiskRowContainer` is pretty simple for the `Sorter` but other intermediaries will need probably need some more specific logic (e.g. appending to values)
</blockquote></details>

OK. I like these semantics. Then can you sketch out the `DiskRowContainer` design and add it to this PR?

---

*[pkg/sql/distsqlrun/disk_map.go, line 68 at r1](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Km2l_z8P9XIdzgCzrFn:-KmCGM6J5W3ZDYCPJEAM:brmoage) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/e0cd2d773bb12569eeef24c4032bef1613ee72c3/pkg/sql/distsqlrun/disk_map.go#L68)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Changed. I assume we will pass in the processor ID as a key prefix?
</blockquote></details>

Yes, that sounds right to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10)*

**Comment by rjnn** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/distsqlrun/disk_map.go, line 83 at r4](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-KmYIu_JS7P9pONquiS0:-KmYIu_JS7P9pONquiS1:b-clmd6w) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/6d83c5e8a90d816d1f4aee1169ed48fa96e422bc/pkg/sql/distsqlrun/disk_map.go#L83)):*
> ```Go
> 	// TODO(asubiotto): Add memory accounting.
> 	store *engine.RocksDB
> }
> ```

add: `prefix uint64`

---

*[pkg/sql/distsqlrun/disk_map.go, line 89 at r4](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-KmYIyS4dRYQ2K2d8ySH:-KmYIyS4dRYQ2K2d8ySI:bx7l9cb) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/6d83c5e8a90d816d1f4aee1169ed48fa96e422bc/pkg/sql/distsqlrun/disk_map.go#L89)):*
> ```Go
> var _ SortedDiskMap = RocksDBMap{}
> 
> func NewRocksDBMap(r *engine.RocksDB) RocksDBMap {
> ```

Have the RocksDBMap also take a `prefix uint64`, and then prepend it to every put, and strip it from every get. Make sure the scans scan such that they don't read past the prefix. This will need a little testing as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10)*

**Comment by rjnn** [comment]
Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions.

---

*[pkg/sql/distsqlrun/disk_map.go, line 157 at r7](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Kmh3x-DMLzzxgXyUy1C:-Kmh3x-DMLzzxgXyUy1D:bxdfpye) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/daa9d3ed2c2f77dd704f4c9182514e27d1a3d0e4/pkg/sql/distsqlrun/disk_map.go#L157)):*
> ```Go
> 
> func (r RocksDBMap) Close() {
> 	// TODO(asubiotto): Close should return errors? What does one do with the
> ```

Log it to the error log. We don't need to do anything more because this eats up disk space, but doesn't really affect anything else.

---

*[pkg/sql/distsqlrun/disk_map_test.go, line 67 at r7](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-Kmh6Y9oacEwXNgsFmQy:-Kmh6Y9oacEwXNgsFmQz:b-d62k7c) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/daa9d3ed2c2f77dd704f4c9182514e27d1a3d0e4/pkg/sql/distsqlrun/disk_map_test.go#L67)):*
> ```Go
> 	rng := rand.New(rand.NewSource(int64(time.Now().UnixNano())))
> 
> 	numKeysToWrite := 100
> ```

crank this way up

---

*[pkg/sql/distsqlrun/disk_row_container.go, line 37 at r7](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-KmhAFu5mZ5TvR7JDwCm:-KmhAFu5mZ5TvR7JDwCn:b-xcpo16) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/daa9d3ed2c2f77dd704f4c9182514e27d1a3d0e4/pkg/sql/distsqlrun/disk_row_container.go#L37)):*
> ```Go
> 	scratchEncRow sqlbase.EncDatumRow
> 
> 	// TODO(asubiotto): The code can be DRYed if we construct a type
> ```

Not a big deal, don't worry about it. This is sadly the state of the codebase everywhere in DistSQL.

---

*[pkg/sql/distsqlrun/disk_row_container.go, line 101 at r7](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-KmhC6c-rAJDXPbCYwhq:-KmhC6c-rAJDXPbCYwhr:b9qsno) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/daa9d3ed2c2f77dd704f4c9182514e27d1a3d0e4/pkg/sql/distsqlrun/disk_row_container.go#L101)):*
> ```Go
> 
> 	for i := 0; i < rowContainer.Len(); i++ {
> 		// TODO(asubiotto): We have to be careful here because we don't want to
> ```

Yeah this is particularly tricksy because the rowContainer might be "tuned" to use a bunch of memory exactly, and we might trip it here.

---

*[pkg/sql/distsqlrun/sorterstrategy.go, line 134 at r7](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-KmhCVR5hBffDMvDMj1e:-KmhCVR6hOeks3Pn-pfs:bhumc86) ([raw file](https://github.com/arjunravinarayan/cockroach/blob/daa9d3ed2c2f77dd704f4c9182514e27d1a3d0e4/pkg/sql/distsqlrun/sorterstrategy.go#L134)):*
> ```Go
> }
> 
> // TODO(asubiotto): The in-memory and disk row containers should be put behind
> ```

This TODO is pressing, should be a high priority to address.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10)*

**Comment by rjnn** [comment]
The last commit is failing a few tests:
```
--- FAIL: TestMemoryGetsFreedOnEachRow (0.19s)
	builtin_mem_usage_test.go:208: Expected statement to OOM, but it didn't
--- FAIL: TestEvaluatedMemoryIsChecked (0.28s)
    --- FAIL: TestEvaluatedMemoryIsChecked/#00 (0.14s)
--- FAIL: TestAggregatesMonitorMemory (0.25s)
	builtin_mem_usage_test.go:93: Expected "SELECT LENGTH(CONCAT_AGG(a)) FROM d.t" to consume too much memory
```

Can you take a look? I'm going to open a new PR to you with some of my code underneath so that you can test end-to-end. I made a few changes to your code to hook it all up.

---

Review status: 0 of 8 files reviewed at latest revision, 9 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/arjunravinarayan/cockroach/10#-:-KmhIqWk7Q0-jtLW1G3y:bll0sx2)*

**Comment by asubiotto** [comment]
Fixed and pushed to your branch

**Comment by rjnn** [comment]
OK. Let's close this PR and have further conversations on #12. Let's take care to rebase into the right commit, because we'll structure them as two separate PRs, and retain the author tags as (1: me), (2,3,4: you).

**Pull request closed without merging**
